<a href="https://colab.research.google.com/github/minerado/ml/blob/main/gpt-implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GPT Implementation

This implementation is based on Andej Karpathy's tutorial [Let's build GPT](https://www.youtube.com/watch?v=kCc8FmEb1nY)

For this exercise, we'll be using the tinyshakespare data as vocabulary:

In [27]:
# Fetch and save data
!wget -q https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

In [28]:
with open('input.txt', 'r') as f:
    text = f.read()

In [29]:
print(f"Length of dataset: {len(text)} characters")

Length of dataset: 1115394 characters


In [30]:
# Let's inspect it
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



## Build the vocabulary

In [31]:
# Unique characters to appear in the data
chars = sorted(set(text))
vocab_size = len(chars)

print(f"Vocabulary: {''.join(chars)}")
print(f"Vocabulary size: {vocab_size}")

Vocabulary: 
 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
Vocabulary size: 65


## Encoding/Decoding functions

In [32]:
# Create mapping from characters to integers
char_dict = {char: i for i, char in enumerate(chars)}
index_dict = {i: char for i, char in enumerate(chars)}

def encode(s): return [char_dict[c] for c in s]
def decode(lst): return ''.join([index_dict[i] for i in lst])

In [33]:
decode(encode("hello world"))

'hello world'

## Build data for training

In [34]:
# Let's now encode the entire text and store it into a tensor
import torch

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [35]:
# Separate train and validation data
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

print(f'Train data shape: {train_data.shape}')
print(f'Validation data shape: {val_data.shape}')

Train data shape: torch.Size([1003854])
Validation data shape: torch.Size([111540])


## Uderstanding block size

In [36]:
## From HuggingFace Docs:
## block_size: This is the maximum sequence length or length of one block of text.
block_size = 8
x = train_data[:block_size]
y = train_data[1:block_size+1]

for i in range(block_size):
  print(f"Input: {x[:i+1].tolist()}; Target: {y[i]}")
print(x, y)

Input: [18]; Target: 47
Input: [18, 47]; Target: 56
Input: [18, 47, 56]; Target: 57
Input: [18, 47, 56, 57]; Target: 58
Input: [18, 47, 56, 57, 58]; Target: 1
Input: [18, 47, 56, 57, 58, 1]; Target: 15
Input: [18, 47, 56, 57, 58, 1, 15]; Target: 47
Input: [18, 47, 56, 57, 58, 1, 15, 47]; Target: 58
tensor([18, 47, 56, 57, 58,  1, 15, 47]) tensor([47, 56, 57, 58,  1, 15, 47, 58])


In [37]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8


def get_batch(data):
  random_idxs = torch.randint(len(train_data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in random_idxs])
  y = torch.stack([data[i+1:i+block_size+1] for i in random_idxs])

  return x, y

xb, yb = get_batch(train_data)

print(f"Input shape: {xb.shape}")
print(f"Input: {xb}")
print(f"Target shape: {yb.shape}")
print(f"Target: {yb}")

Input shape: torch.Size([4, 8])
Input: tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
Target shape: torch.Size([4, 8])
Target: tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


In [83]:
import torch
from torch import nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding_table = nn.Embedding(vocab_size, vocab_size)

  def forward(self, i, target=None):
    logits = self.embedding_table(i)

    if target is None:
      loss = None
    else:
      loss = F.cross_entropy(logits.permute(0, 2, 1), target)

    return logits, loss

  def generate(self, i, max_new_tokens):
    # idx is (B, T) array of indices
    for _ in range(max_new_tokens):
      # get predictions
      logits, loss = self(i)
      # focus only on the last time step
      logits = logits[:, -1, :]
      # apply softmax to get probs
      probs = F.softmax(logits, )


In [84]:
bm = BigramLanguageModel(vocab_size)
out, loss = bm(xb, yb)
print(out.shape)
print(loss)

torch.Size([4, 8, 65])
tensor(4.8786, grad_fn=<NllLoss2DBackward0>)


In [92]:
F.softmax(out, dim=1)

print(out)
out[:, -1, :]

tensor([[[-1.5101, -0.0948,  1.0927,  ..., -0.6126, -0.6597,  0.7624],
         [ 0.3323, -0.0872, -0.7470,  ..., -0.6716, -0.9572, -0.9594],
         [ 0.2475, -0.6349, -1.2909,  ...,  1.3064, -0.2256, -1.8305],
         ...,
         [ 0.5978, -0.0514, -0.0646,  ..., -1.4649, -2.0555,  1.8275],
         [ 1.0901,  0.2170, -2.9996,  ..., -0.5472, -0.8017,  0.7761],
         [ 0.3323, -0.0872, -0.7470,  ..., -0.6716, -0.9572, -0.9594]],

        [[ 1.0541,  1.5018, -0.5266,  ...,  1.8574,  1.5249,  1.3035],
         [-0.1324, -0.5489,  0.1024,  ..., -0.8599, -1.6050, -0.6985],
         [-0.6722,  0.2322, -0.1632,  ...,  0.1390,  0.7560,  0.4296],
         ...,
         [ 1.0901,  0.2170, -2.9996,  ..., -0.5472, -0.8017,  0.7761],
         [ 1.1513,  1.0539,  3.4105,  ..., -0.5686,  0.9079, -0.1701],
         [ 0.2475, -0.6349, -1.2909,  ...,  1.3064, -0.2256, -1.8305]],

        [[-0.2103,  0.4481,  1.2381,  ...,  1.3597, -0.0821,  0.3909],
         [ 0.2475, -0.6349, -1.2909,  ...,  1

tensor([[ 0.3323, -0.0872, -0.7470, -0.6074,  0.3418,  0.5343,  0.3957, -0.4919,
         -0.0894, -1.3886,  1.2835, -0.3975,  2.0152,  1.6773, -0.3833,  1.5728,
          1.9458,  0.7247, -0.4834, -0.3263,  0.3193, -0.4198, -0.6435, -0.3311,
          0.7554, -1.2385,  0.4067,  0.9982, -0.6511,  1.2450,  0.2804,  0.8371,
         -0.4119,  0.2115, -0.6240,  0.0203, -0.3418,  1.4934,  1.7307,  1.3354,
         -0.2712,  0.4902,  0.6600, -1.6321, -0.7858,  1.7688,  2.6160, -0.5767,
         -0.3628, -2.7428,  0.7428,  0.0737,  0.2050, -0.5497,  2.1261, -0.9240,
          0.1048,  0.8324,  1.4287, -0.7789,  2.9275, -0.8525, -0.6716, -0.9572,
         -0.9594],
        [ 0.2475, -0.6349, -1.2909,  1.1822,  0.1479, -0.4333, -0.8269,  0.0728,
         -1.2982,  0.3960, -1.2460,  0.1458, -0.5699, -1.3561, -0.3812, -0.8515,
          1.1918, -0.8108, -0.1733, -0.4703, -0.6000, -1.3636, -1.0889,  1.0108,
          0.8543, -0.0441,  1.8017,  0.6014, -2.5448, -0.4865,  2.6412,  1.6053,
         

In [ ]:
1